name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 11
      - name: Install dependencies
        run: npm install --build-from-source
      - name: Test
        run: npm run test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: logs
