name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install --build-from-source
      - name: Test
        run: npm run test:local
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: logs
